[package]
name = "day-09"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "benchmarks"
harness = false

[dependencies]
divan = "0.1.17"
nom = "7.1.3"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
